### ISSUE TITLE
Game freezes after suspending and waking the device

### ISSUE THREAD

**Issue by JarlPenguin** [juanmuscaria/blockheads-patch#1]
Not sure if this is fixable even.

**Comment by juanmuscaria** [comment]
I'll take a look on it, random guess but I think it's caused by the same bug as the webview

**Comment by juanmuscaria** [comment]
~~Game keeps on an infinite loop spamming `WifiVendorHal: getWifiLinkLayerStats_1_5_Internal(l.1191) failed {.code = ERROR_NOT_SUPPORTED, .description = }` on the logcat~~ Seems unrelated, after probing around the activity seems like it's freezing at native code 
after even more digging, seems like it freezes at https://github.com/AndroidSDKSources/android-sdk-sources-for-api-level-32/blob/f31e558b3e840d4c1cc7bd6e917b4648d98749d1/android/view/WindowManagerGlobal.java#L683

**Comment by JarlPenguin** [comment]
Hmm

**Comment by JarlPenguin** [comment]
The game's target SDK level is 27, so might be worth checking if the logic is same there

**Comment by juanmuscaria** [comment]
Alright, I think got what is the problem, on older versions android would not check the thread of a view and  just stop it, now on newer versions it will schedule the stop on the handler of that view
The gl surfaceview runs on a "main thread" which is not the android main thread, but apparently it waits the android ui thread to notify it's ready to go native. now when you try to suspend the game you now have the main thread waiting the ui thread to notify it to go native, and the ui thread waiting the main thread to run the stop code of the view

**Comment by juanmuscaria** [comment]
Relevant stacktraces:
```
"main" prio=5 tid=1 Waiting
  | group="main" sCount=1 ucsCount=0 flags=1 obj=0x71afbef0 self=0xf1c9de00
  | sysTid=31897 nice=-10 cgrp=default sched=0/0 handle=0xf232a474
  | state=S schedstat=( 1119034300 36759461 985 ) utm=89 stm=22 core=2 HZ=100
  | stack=0xff39a000-0xff39c000 stackSize=8188KB
  | held mutexes=
  at java.lang.Object.wait(Native method)
  - waiting on <0x0644711d> (a android.os.Handler$BlockingRunnable)
  at java.lang.Object.wait(Object.java:442)
  at java.lang.Object.wait(Object.java:568)
  at android.os.Handler$BlockingRunnable.postAndWait(Handler.java:991)
  - locked <0x0644711d> (a android.os.Handler$BlockingRunnable)
  at android.os.Handler.runWithScissors(Handler.java:606)
  at android.view.WindowManagerGlobal.setStoppedState(WindowManagerGlobal.java:815)
  at android.app.Activity.performStop(Activity.java:8530)
  at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5705)
  at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5649)
  at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5750)
  at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
  at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
  at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loopOnce(Looper.java:226)
  at android.os.Looper.loop(Looper.java:313)
  at android.app.ActivityThread.main(ActivityThread.java:8663)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
  
"MainThread" prio=5 tid=18 Waiting
  | group="main" sCount=1 ucsCount=0 flags=1 obj=0x13080000 self=0xefdbca00
  | sysTid=31941 nice=0 cgrp=default sched=0/0 handle=0xbf45e1c0
  | state=S schedstat=( 5234411924 95917001 2534 ) utm=398 stm=124 core=3 HZ=100
  | stack=0xbee5b000-0xbee5d000 stackSize=6156KB
  | held mutexes=
  at java.lang.Object.wait(Native method)
  - waiting on <0x01bc0219> (a java.lang.Object)
  at java.lang.Object.wait(Object.java:442)
  at java.lang.Object.wait(Object.java:568)
  at com.apportable.gl.GLSurfaceView.readySurface(GLSurfaceView.java:645)
  - locked <0x01bc0219> (a java.lang.Object)
  at com.apportable.gl.GLSurfaceView$1$1.run(GLSurfaceView.java:98)
  at com.apportable.MainThread.runTickActions(MainThread.java:128)
  at com.apportable.MainThread.tick(MainThread.java:113)
  at com.apportable.MainThread.nativeRun(Native method)
  at com.apportable.MainThread.access$100(MainThread.java:15)
  at com.apportable.MainThread$2.run(MainThread.java:83)
  at android.os.Handler.handleCallback(Handler.java:938)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loopOnce(Looper.java:226)
  at android.os.Looper.loop(Looper.java:313)
  at com.apportable.MainThread$1.run(MainThread.java:42)
  at java.lang.Thread.run(Thread.java:920)
  ```

**Comment by JarlPenguin** [comment]
Does that mean messing with the source code is required? I tried looking for apportable's SDK but it's long gone.

**Comment by juanmuscaria** [comment]
Yes, I tried removing the synchronization locks, but then when the thread goes "native" it also tries to lock again using JNI in a special back and forth between the fake main thread and the actual main thread. I'm unsure if that would even be fixable without a major rewrite of apportable itself. I'll see what I can do when I get some free time again

**Comment by JarlPenguin** [comment]
Scoured the internet for any download links but couldn't find any :/ Makes sense I guess since they went bankrupt some time ago
