### ISSUE TITLE
The game still crashes and white screen

### ISSUE THREAD

**Issue by PeteLJ** [juanmuscaria/blockheads-patch#4]
I have successfully applied your patch.
However, when I open the blockheads 1.7.6 app, there is still a few seconds of white screen. And after the white screen, the game will rotate into landscape mode which likely causes it to crash. I realised that the game only crashes when it changes orientation.

Are you able to fix this issue? Im running on Android 11 currently.

**Comment by juanmuscaria** [comment]
If you have adb/root, could you grab relevant crash information from logcat?

**Comment by PeteLJ** [comment]
I do not have a rooted phone. But I managed to get crash logs by using adb.

**When I start the game while holding my phone in portrait orientation:** 

Process: com.noodlecake.blockheads
PID: 22392
UID: 10686
Flags: 0x1a98bc44
Package: com.noodlecake.blockheads v1564553369 (1.7.6)
Foreground: Yes
Process-Runtime: 1646588936
Build: samsung/a52xqnaxx/a52xq:11/RP1A.200720.012/A526BXXU1AUJ7:user/release-keys 

android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:10750)
at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:2209)
at android.view.ViewRootImpl.updateConfiguration(ViewRootImpl.java:5838)
at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:6773)
at android.app.ActivityThread$ActivityClientRecord.lambda$init$0$ActivityThread$ActivityClientRecord(ActivityThread.java:719)
at android.app.-$$Lambda$ActivityThread$ActivityClientRecord$HOrG1qglSjSUHSjKBn2rXtX0gGg.onConfigurationChanged(Unknown Source:2)
at android.view.ViewRootImpl.performConfigurationChange(ViewRootImpl.java:5787)
at android.view.ViewRootImpl.access$900(ViewRootImpl.java:256)
at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:6080)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8653)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 

**When I start the game up while holding my phone in landscape orientation, the game starts up fully and brings me to the lobby. However, when I change orientation while in game, it will crash immediately:**

Process: com.noodlecake.blockheads
PID: 30806
UID: 10686
Flags: 0x1a98bc44
Package: com.noodlecake.blockheads v1564553369 (1.7.6)
Foreground: Yes
Process-Runtime: 1646626456
Build: samsung/a52xqnaxx/a52xq:11/RP1A.200720.012/A526BXXU1AUJ7:user/release-keys 

android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:10750)
at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:2209)
at android.view.ViewRootImpl.updateConfiguration(ViewRootImpl.java:5838)
at android.app.ActivityThread.handleActivityConfigurationChanged(ActivityThread.java:6773)
at android.app.servertransaction.ActivityConfigurationChangeItem.execute(ActivityConfigurationChangeItem.java:51)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8653)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by juanmuscaria** [comment]
Random guess, but the game for some reason uses a "main thread" created separately and breaks a lot of common thread safety patterns instead of using its original thread, maybe something changed on newer android versions that disallows its bad multithreading, last known working android version is 10.

Good thing, my new phone is using android 11, and I figured out how to use frida without rooting it, I'll see what I can do about that crash.

**Comment by PeteLJ** [comment]
Oh, I see. Thanks so much for your efforts to help revive this game! I really appreciate it 😊

**Comment by redthing1** [comment]
Great
